[options]
db_host = localhost
db_port = 5432
addons_path = /home/mohamed-gomaa/Desktop/Odoo_Projects/classmates/odoo-18.0/addons, /home/mohamed-gomaa/Desktop/Odoo_Projects/classmates/odoo-18.0/odoo/addons, /home/mohamed-gomaa/Desktop/Odoo_Projects/classmates/custom_addons

db_user = mohamed-gomaa
db_name = classmates_db
db_password = your_password